---
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.1.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(?:ts|js|vue)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.21.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/c18t/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: yamllint
      - id: hadolint
