---
name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Registry
        run: docker login -u $GITHUB_ACTOR -p $GITHUB_TOKEN docker.pkg.github.com
      - name: echo version tag
        run: echo $GITHUB_REF
      #- name: Build the Docker image
      #  run: docker build . --tag docker.pkg.github.com/${GITHUB_REF,,}
      #- name: Push the image to GitHub Packages Registry
      #  run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${GITHUB_REPOSITORY,,#*/}:${GITHUB_REF,,}
