---
name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Make image name and version
        run: |
          REPOS_L=${GITHUB_REPOSITORY,,}
          IMAGE_NAME=docker.pkg.github.com/${REPOS_L}/${REPOS_L#*/}
          IMAGE_VERSION=${GITHUB_REF#refs/tags/v}
          echo ${IMAGE_NAME}:${IMAGE_VERSION} > specific-version.txt
          echo ${IMAGE_NAME}:latest > latest-version.txt
      - name: Build the Docker image
        run: docker build . --tag $(cat specific-version.txt)
      - name: Add latest version tag
        run: docker tag $(cat specific-version.txt) $(cat latest-version.txt)
      - name: Push the image to GitHub Packages
        run: docker push $(cat specific-version.txt)
      - name: Push the image to GitHub Packages as latest version
        run: docker push $(cat latest-version.txt)
