---
name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Registry
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Make image name and version
        run: REPOS_L=${GITHUB_REPOSITORY,,}; IMAGE_NAME=docker.pkg.github.com/${REPOS_L}/${REPOS_L#*/}; IMAGE_VERSION=${GITHUB_REF#ref/tags/v}
      - name: Build the Docker image
        run: echo ${IMAGE_NAME}:${IMAGE_VERSION}; docker build . --tag ${IMAGE_NAME}:${IMAGE_VERSION}
      - name: Push the image to GitHub Packages Registry
        run: docker push ${IMAGE_NAME}:${IMAGE_VERSION}
      - name: Build the Docker image as latest version
        run: docker build . --tag ${IMAGE_NAME}:latest
      - name: Push the image to GitHub Packages Registry as latest version
        run: docker push ${IMAGE_TAG}:latest
